In [65]:
import pandas as pd
import numpy as np
data_dir = "./dataset/"

In [66]:
std_labtest = pd.read_csv(data_dir + "std/LabtestStd.csv")
std_attr = pd.read_csv(data_dir + "std/SelectedAttribute.csv")
s1 = pd.read_csv(data_dir + "std/data_categories-s1.csv")
s2 = pd.read_csv(data_dir + "std/data_categories-s2.csv")

In [67]:
s1

,test_key,test_name,attr_key,attribute,data_type,unit,unique
0,10655,CBC,13387,ESR,Neumerical,mm in 1st hour,['.' '02' '03' '04' '05' '06' '07' '08' '09' '...
1,10994,Complete Urine Analysis (Urine R/E),14491,Protein,Categorical,Null,['(+)' '(++)' '(+++)' '(++++)' '+' '++' '+++' ...
2,10994,Complete Urine Analysis (Urine R/E),14498,Blood,Categorical,Null,['(+)' '(++)' '(+++)' '+' '++' '+++' 'Absent' ...
3,10994,Complete Urine Analysis (Urine R/E),14499,Appearance,Categorical,Null,['Clear' 'Hazy' 'Turbid']
4,10994,Complete Urine Analysis (Urine R/E),14501,Colour,Categorical,Null,['Amber' 'AMBER' 'Dark Brown' 'Deep starw' 'De...
5,10994,Complete Urine Analysis (Urine R/E),14512,Uric Acid,Categorical,Null,['(+)' '(++)' 'A few' 'Few' 'Nil']
6,10994,Complete Urine Analysis (Urine R/E),14517,Sugar,Categorical,Null,['(+)' '(++)' '(+++)' '(++++)' '+' '++' '+++' ...
7,10994,Complete Urine Analysis (Urine R/E),14521,R B C,Categorical,/LPF,['Nil']
8,10994,Complete Urine Analysis (Urine R/E),14522,W B C,Categorical,/LPF,['Nil']
9,10994,Complete Urine Analysis (Urine R/E),14526,Bilirubin,Categorical,Null,['(+)' '+' 'Nil' 'Normal' 'Not done' 'Not Done']
10,10937,Electrolytes Serum,14366,Sodium,Neumerical,mmol/L,['104' '105' '106' '107' '108' '109' '110' '11...
11,10937,Electrolytes Serum,14367,Potassium,Categorical,mmol/L,['1.6' '1.7' '1.8' '1.9' '2.0' '2.1' '2.2' '2....
12,10693,FBG - Fasting blood glucose,13498,Blood glucose level,Neumerical,mmol/L,['10' '10.0' '10.1' '10.2' '10.3' '10.4' '10.5...
13,10057,Grouping + Cross Matching + Screening,10431,Blood Group :,Categorical,Null,"['""A""' 'AB' '""AB""' ""''B''"" '""B""' 'O' ""''O''"" '..."
14,10057,Grouping + Cross Matching + Screening,10432,Rh Type :,Categorical,Null,['Negative' 'positive' 'Positive']
15,10057,Grouping + Cross Matching + Screening,10440,1. HBsAg,Categorical,Null,['Negative' 'Positive']
16,10816,HbA1c,13952,HbA1c,Neumerical,%,['10.0' '10.1' '10.2' '10.3' '10.4' '10.5' '10...
17,10626,Lipid Profile Serum (R),13068,Total Cholesterol,Neumerical,mg/dL,['100' '101' '102' '103' '104' '105' '106' '10...
18,10626,Lipid Profile Serum (R),13069,HDL Cholesterol,Neumerical,mg/dL,['102' '10.7' '110' '15.4' '15.5' '16' '17' '1...
19,10626,Lipid Profile Serum (R),13070,LDL Cholesterol,Neumerical,mg/dL,['-' '---' '**' '***' '10' '100' '101' '102' '...
20,10626,Lipid Profile Serum (R),13071,Triglycerides,Neumerical,mg/dL,['100' '102' '103' '104' '105' '1050' '106' '1...

In [68]:
s2

,test_id,test_name,attr_id,attr_name,unit,unique
0,101497,CBC,104291,ESR,mm in 1st hour,['76' '25' '52' '32' '67' '03' '09' '64' '30' ...
1,5003345,Complete Urine Analysis (Urine R/E),3000003,Protein,NaN,['Trace' 'Nil' '++' '+' 'nan' '0' 'Not Done' '...
2,5003345,Complete Urine Analysis (Urine R/E),3000016,Blood,NaN,['nan' 'Nil' 'Not done' 'Trace' '3+' '+++' '(+...
3,5003345,Complete Urine Analysis (Urine R/E),3000017,Appearance,NaN,['nan' 'Clear' 'Hazy' 'Turbid']
4,5003345,Complete Urine Analysis (Urine R/E),3000020,Colour,NaN,['L YELLOW' 'Straw' 'STRAW' 'Yellow' 'nan' 'AM...
5,5003345,Complete Urine Analysis (Urine R/E),3000031,Uric Acid,NaN,['nan' 'Nil' '0' '(+)' '(++)' 'Few' '(+++)' 'A...
6,5003345,Complete Urine Analysis (Urine R/E),3000037,Sugar,NaN,['Nil' '+++' 'nan' '++++' '0' 'Trace' 'Not Don...
7,5003345,Complete Urine Analysis (Urine R/E),3000042,R B C,/LPF,['nan' 'Nil' '0']
8,5003345,Complete Urine Analysis (Urine R/E),3000043,W B C,/LPF,['nan' 'Nil' '0']
9,5003345,Complete Urine Analysis (Urine R/E),3000067,Bilirubin,NaN,['Nil' 'Not done' 'Not Done' 'nan' '0' '+' 'No...
10,101304,Electrolytes Serum,101214,Sodium,mmol/L,['143' '146' '155' '140' '138' '177' '130' '14...
11,101304,Electrolytes Serum,102050,Potassium,mmol/L,['3.0' '3.3' '2.9' '4.1' '5.1' '2.8' '4.3' '4....
12,101602,Fasting Blood Sugar (FBS),101211,Fasting Blood Sugar,mmol/L,['5.3' '6.1' '13.1' '5.8' '4.7' '6.3' '6.7' '5...
13,100824,Grouping + Cross Matching + Screening,3002195,Blood Group :,NaN,"['""A""' 'nan' '""AB""' '""B""' '""O""' '""A\'' '""O ""' ..."
14,100824,Grouping + Cross Matching + Screening,3002196,Rh Type :,NaN,['Negative' 'nan' 'Positive']
15,100824,Grouping + Cross Matching + Screening,3002201,Blood Group :,NaN,"['""A""' 'nan' '""AB""' '""B""' '""O""' '""A\'' ""''B''""..."
16,100824,Grouping + Cross Matching + Screening,3002202,Rh Type :,NaN,['Negative' 'nan' 'Positive' 'Positve' 'positi...
17,100824,Grouping + Cross Matching + Screening,3002206,1. HBsAg,NaN,['Negative' 'nan' 'Positive' 'Not done' 'Not D...
18,101305,HbA1c,102057,HbA1c,%,['10.3' '7.1' '6.7' '7.6' '6.1' '8.2' '5.9' '6...
19,100921,Lipid Profile Serum (R),102084,Total Cholesterol,mg/dL,['238' '224' '152' '181' '173' '159' '677' '23...
20,100921,Lipid Profile Serum (R),103729,HDL Cholesterol,mg/dL,['36' '50.3' '38.2' '30.1' '51' '32.7' '20' '5...
21,100921,Lipid Profile Serum (R),103730,LDL Cholesterol,mg/dL,['158' '138' '76' '103' '99' '91' '**' '134' '...
22,100921,Lipid Profile Serum (R),103731,Triglycerides,mg/dL,['218' '177' '186' '237' '131' '178' '5747' '7...

In [69]:
s1.columns = ['test_key', 'test_name', 'attr_key', 'attr_name', 'data_type', 'unit',
       'unique']
s2 = s2.merge(s1[['test_key', 'test_name', 'attr_key', 'attr_name', 'data_type']], on=['test_name', 'attr_name'])
s2

,test_id,test_name,attr_id,attr_name,unit,unique,test_key,attr_key,data_type
0,101497,CBC,104291,ESR,mm in 1st hour,['76' '25' '52' '32' '67' '03' '09' '64' '30' ...,10655,13387,Neumerical
1,5003345,Complete Urine Analysis (Urine R/E),3000003,Protein,NaN,['Trace' 'Nil' '++' '+' 'nan' '0' 'Not Done' '...,10994,14491,Categorical
2,5003345,Complete Urine Analysis (Urine R/E),3000016,Blood,NaN,['nan' 'Nil' 'Not done' 'Trace' '3+' '+++' '(+...,10994,14498,Categorical
3,5003345,Complete Urine Analysis (Urine R/E),3000017,Appearance,NaN,['nan' 'Clear' 'Hazy' 'Turbid'],10994,14499,Categorical
4,5003345,Complete Urine Analysis (Urine R/E),3000020,Colour,NaN,['L YELLOW' 'Straw' 'STRAW' 'Yellow' 'nan' 'AM...,10994,14501,Categorical
5,5003345,Complete Urine Analysis (Urine R/E),3000031,Uric Acid,NaN,['nan' 'Nil' '0' '(+)' '(++)' 'Few' '(+++)' 'A...,10994,14512,Categorical
6,5003345,Complete Urine Analysis (Urine R/E),3000037,Sugar,NaN,['Nil' '+++' 'nan' '++++' '0' 'Trace' 'Not Don...,10994,14517,Categorical
7,5003345,Complete Urine Analysis (Urine R/E),3000042,R B C,/LPF,['nan' 'Nil' '0'],10994,14521,Categorical
8,5003345,Complete Urine Analysis (Urine R/E),3000043,W B C,/LPF,['nan' 'Nil' '0'],10994,14522,Categorical
9,5003345,Complete Urine Analysis (Urine R/E),3000067,Bilirubin,NaN,['Nil' 'Not done' 'Not Done' 'nan' '0' '+' 'No...,10994,14526,Categorical
10,101304,Electrolytes Serum,101214,Sodium,mmol/L,['143' '146' '155' '140' '138' '177' '130' '14...,10937,14366,Neumerical
11,101304,Electrolytes Serum,102050,Potassium,mmol/L,['3.0' '3.3' '2.9' '4.1' '5.1' '2.8' '4.3' '4....,10937,14367,Categorical
12,100824,Grouping + Cross Matching + Screening,3002195,Blood Group :,NaN,"['""A""' 'nan' '""AB""' '""B""' '""O""' '""A\'' '""O ""' ...",10057,10431,Categorical
13,100824,Grouping + Cross Matching + Screening,3002201,Blood Group :,NaN,"['""A""' 'nan' '""AB""' '""B""' '""O""' '""A\'' ""''B''""...",10057,10431,Categorical
14,100824,Grouping + Cross Matching + Screening,3002196,Rh Type :,NaN,['Negative' 'nan' 'Positive'],10057,10432,Categorical
15,100824,Grouping + Cross Matching + Screening,3002202,Rh Type :,NaN,['Negative' 'nan' 'Positive' 'Positve' 'positi...,10057,10432,Categorical
16,100824,Grouping + Cross Matching + Screening,3002206,1. HBsAg,NaN,['Negative' 'nan' 'Positive' 'Not done' 'Not D...,10057,10440,Categorical
17,101305,HbA1c,102057,HbA1c,%,['10.3' '7.1' '6.7' '7.6' '6.1' '8.2' '5.9' '6...,10816,13952,Neumerical
18,100921,Lipid Profile Serum (R),102084,Total Cholesterol,mg/dL,['238' '224' '152' '181' '173' '159' '677' '23...,10626,13068,Neumerical
19,100921,Lipid Profile Serum (R),103729,HDL Cholesterol,mg/dL,['36' '50.3' '38.2' '30.1' '51' '32.7' '20' '5...,10626,13069,Neumerical
20,100921,Lipid Profile Serum (R),103730,LDL Cholesterol,mg/dL,['158' '138' '76' '103' '99' '91' '**' '134' '...,10626,13070,Neumerical
21,100921,Lipid Profile Serum (R),103731,Triglycerides,mg/dL,['218' '177' '186' '237' '131' '178' '5747' '7...,10626,13071,Neumerical

In [70]:
s1.columns

Index(['test_key', 'test_name', 'attr_key', 'attr_name', 'data_type', 'unit',
       'unique'],
      dtype='object')

### Generate Clinical Test Std data
Columns:
 _id,	lab_name,	test_key,	test_name,	attribute_key,	attribute_name,	result_type,	loinc_code,	loinc_name,	component,	short_name,	class_name,	unit(UCUM)

In [71]:
# print(s1)
def get_type(test_key, attr_key):
    cat = s1[(s1['test_key']==test_key) & (s1['attr_key']==attr_key)]
#     print(cat['data_type'].values[0])
    return cat['data_type'].values[0]

In [72]:
# del std_attr['@']
std_attr['_id'] = std_attr.index + 1001
# print(std_attr)
std_attr['result_type'] = std_attr.apply(lambda x: get_type(x.test_key, x.attribute_key), axis=1)
std_attr

,lab_name,test_key,test_name,attribute_key,attribute_name,code,loinc_name,component,short_name,class_name,unit(UCUM),_id,result_type
0,Haematology,10655,CBC,13387,ESR,30341-2,Erythrocyte sedimentation rate,Erythrocyte sedimentation rate,ESR Bld Qn,HEM/BC,mm/h,1001,Neumerical
1,Clinical Pathology,10994,Complete Urine Analysis (Urine R/E),14491,Protein,2887-8,Protein [Presence] in Urine,Protein,Prot Ur Ql,UA,NaN,1002,Categorical
2,Clinical Pathology,10994,Complete Urine Analysis (Urine R/E),14498,Blood,53963-5,Blood [Presence] in Urine by Visual,Blood,Blood Ur Ql Visual,UA,NaN,1003,Categorical
3,Clinical Pathology,10994,Complete Urine Analysis (Urine R/E),14499,Appearance,5767-9,Appearance of Urine,Appearance,Appearance Ur,SPEC,NaN,1004,Categorical
4,Clinical Pathology,10994,Complete Urine Analysis (Urine R/E),14501,Colour,5778-6,Color of Urine,Color,Color Ur,SPEC,NaN,1005,Categorical
5,Clinical Pathology,10994,Complete Urine Analysis (Urine R/E),14517,Sugar,25428-4,Glucose [Presence] in Urine by Test strip,Glucose,Glucose Ur Ql Strip,UA,NaN,1006,Categorical
6,Clinical Pathology,10994,Complete Urine Analysis (Urine R/E),14521,R B C,33051-4,Erythrocytes [Presence] in Urine,Erythrocytes,RBC Ur Ql,UA,NaN,1007,Categorical
7,Clinical Pathology,10994,Complete Urine Analysis (Urine R/E),14522,W B C,33052-2,Leukocytes [Presence] in Urine,Leukocytes,WBC Ur Ql,UA,NaN,1008,Categorical
8,Clinical Pathology,10994,Complete Urine Analysis (Urine R/E),14526,Bilirubin,5770-3,Bilirubin.total [Presence] in Urine by Test strip,Bilirubin,Bilirub Ur Ql Strip,UA,NaN,1009,Categorical
9,Biochemistry,10937,Electrolytes Serum,14366,Sodium,2951-2,Sodium [Moles/volume] in Serum or Plasma,Sodium,Sodium SerPl-sCnc,CHEM,mmol/L,1010,Neumerical
10,Biochemistry,10937,Electrolytes Serum,14367,Potassium,2823-3,Potassium [Moles/volume] in Serum or Plasma,Potassium,Potassium SerPl-sCnc,CHEM,mmol/L,1011,Categorical
11,Biochemistry,10693,FBG - Fasting blood glucose,13498,Blood glucose level,76629-5,Fasting glucose [Moles/volume] in Blood,Glucose^post CFst,Glucose p fast Bld-sCnc,CHEM,mmol/L,1012,Neumerical
12,Biochemistry,10816,HbA1c,13952,HbA1c,86910-7,Hemoglobin A1c/Hemoglobin.total goal Blood,Hemoglobin A1c/Hemoglobin.total goal,Hgb A1c goal MFr Bld,CLIN,%,1013,Neumerical
13,Biochemistry,10626,Lipid Profile Serum (R),13070,LDL Cholesterol,13457-7,Cholesterol in LDL [Mass/volume] in Serum or P...,Lipid panel with direct LDL,Cholesterol.in LDL,CHEM,mg/dL,1014,Neumerical
14,Biochemistry,10626,Lipid Profile Serum (R),13069,HDL Cholesterol,2085-9,Cholesterol in HDL [Mass/volume] in Serum or P...,Cholesterol.in HDL,HDLc SerPl-mCnc,CHEM,mg/dL,1015,Neumerical
15,Biochemistry,10626,Lipid Profile Serum (R),13071,Triglycerides,2571-8,Triglyceride [Mass/volume] in Serum or Plasma,Triglyceride,Trigl SerPl-mCnc,CHEM,mg/dL,1016,Neumerical
16,Biochemistry,10626,Lipid Profile Serum (R),13068,Total Cholesterol,2093-3,Cholesterol [Mass/volume] in Serum or Plasma,Cholesterol,Cholest SerPl-mCnc,CHEM,mg/dL,1017,Neumerical
17,BLOOD TRANSFUSION,10057,Grouping + Cross Matching + Screening,10431,Blood Group :,883-9,ABO group [Type] in Blood,ABO group,ABO Group Bld,BLDBK,NaN,1018,Categorical
18,BLOOD TRANSFUSION,10057,Grouping + Cross Matching + Screening,10432,Rh Type :,10331-7,Rh [Type] in Blood,Rh,Rh Bld,BLDBK,NaN,1019,Categorical
19,BLOOD TRANSFUSION,10057,Grouping + Cross Matching + Screening,10440,1. HBsAg,5195-3,Hepatitis B virus surface Ag [Presence] in Serum,Hepatitis B virus surface Ag,HBV surface Ag Ser Ql,MICRO,NaN,1020,Categorical

### Generate Test Name (All possible)
Columns:	_id,	test_key,	name,	ref,	ref_code

In [58]:
del std_labtest["@"]

In [73]:
std_labtest

,lab_name,test_key,test_name,specimen,snomed_name,snomed_ct_id,iccdrb_name,@
0,Haematology,10655,CBC,BLOOD,"Complete blood count, CBC, FBC - Full blood count",26604007,Complete Blood Count,NaN
1,Clinical Pathology,10994,Complete Urine Analysis (Urine R/E),URINE,"Urinalysis, Urinalysis procedure",27171005,Urine Analysis,NaN
2,Microbiology,10252,Urine for C/S,URINE,"Urine culture, Microbial urine culture",117010004,Urine for CS,NaN
3,Microbiology,10217,Blood for C/S,BLOOD,"Blood culture, BC - Blood culture",30088009,Blood for CS,NaN
4,Clinical Pathology,10616,Urine R/M/E,URINE,Urine examination,167217005,Urine RME,NaN
5,Biochemistry,10937,Electrolytes Serum,BLOOD.,"Electrolytes measurement, serum, Serum electro...",20109005,Electrolyte,NaN
6,BLOOD TRANSFUSION,10057,Grouping + Cross Matching + Screening,BLOOD,"Blood group typing, Antigen typing, blood grou...",44608003,Blood Grouping & Rh Typing,NaN
7,Clinical Pathology,10617,Stool R/E,STOOL,"Stool microscopy, Microscopic examination of s...",252393000,Stool RME,NaN
8,Microbiology,10157,Stool for C/S,STOOL,"Stool culture, Feces culture, Microbial stool...",117028002,"Stool CS for Sal., Shig. & Campy spp",NaN
9,Biochemistry,10899,Serum creatinine level,BLOOD,"Serum creatinine level - finding, Finding of ...",365757006,Creatinine,NaN
10,Biochemistry,11079,"Renal Function Test (Urea, Creatinine, Electro...",BLOOD,"Renal function study, Renal function study (na...",44277000,NaN,NaN
11,Biochemistry,10191,Lipid Profile Serum (F),BLOOD.,"Fasting lipid profile, FLP - Fasting lipid pro...",252150008,Lipid Profile,NaN
12,Serology,10550,Prothrombin Time (PT),BLOOD,"Prothrombin time, PT - Prothrombin time, PT a...",396451008,Prothrombin Time (PT/INR),NaN
13,Biochemistry,10453,RBG - Random blood glucose,BLOOD,"Random blood glucose measurement, RBG - Rando...",271061004,Glucose ( R),NaN
14,Haematology,10664,Blood Film (PBF),WHOLE BLOOD,"Peripheral blood smear interpretation, Periphe...",14768001,Cell Morphology (PBF),NaN
15,Biochemistry,10921,ALT(SGPT) Serum,BLOOD,Alanine aminotransferase (serum glutamic-pyru...,166645004,ALT (SGPT),NaN
16,Microbiology,10577,Sputum for C/S,SPUTUM.,"Sputum sent for C/S, Sputum sent for culture a...",168302007,Sputum for CS,NaN
17,Biochemistry,10626,Lipid Profile Serum (R),BLOOD,Lipid panel,16254007,Lipid Profile,NaN
18,Microbiology,10735,Tracheal Aspirate for C/S,TRACHEAL ASPIRATE,"Specimen from trachea obtained by aspiration, ...",445447003,Tracheal aspirate for CS,NaN
19,Biochemistry,10914,Blood Gas Analysis Arterial (ABG),BLOOD.,"Analysis of arterial blood gases and pH, ABG -...",60170009,-,NaN
20,Immunology,10531,CRP (C-Reactive Protein),BLOOD,"C reactive protein, C-reactive protein, CRP...",61425002,CRP (Quantitative),NaN
21,BLOOD TRANSFUSION,10793,Grouping+ICT+Cross Matching + Screening,BLOOD,"Blood group typing, Antigen typing, blood grou...",44608003,Blood Grouping & Rh Typing,NaN
22,Immunology,10309,TSH,BLOOD,"Thyrotrophin, TSH, Thyroid stimulating hormon...",65428006,TSH,NaN
23,Biochemistry,10693,FBG - Fasting blood glucose,BLOOD,"Fasting blood glucose measurement, Fasting blo...",271062006,Glucose (F),NaN
24,Biochemistry,10816,HbA1c,WHOLE BLOOD,"HBA1c target, Hemoglobin A1c (HBA1c) target, H...",408591000,HbA1C,NaN

In [74]:
test_name = std_attr[['test_key', 'test_name']]
test_name = test_name.drop_duplicates(subset=['test_key', 'test_name'])
test_name.apply(lambda x: get_testname_syno(x.test_key), axis=1)

0     None
1     None
9     None
11    None
12    None
13    None
17    None
dtype: object

In [61]:
test_keys = []
name = []
ref = []
ref_code = []
def get_testname_syno(test_key):
#     print(test_key)
    row = std_labtest[std_labtest['test_key']==test_key]
    snomed_ct = row['snomed_name'].values[0].split(',')
    snomed_id = row['snomed_ct_id'].values[0]
    for s in snomed_ct:
        test_keys.append(test_key)
        name.append(s.strip())
        ref.append('SNOMED CT')
        ref_code.append(snomed_id)
    # Icddrb term
    test_keys.append(test_key)
    name.append(row['iccdrb_name'].values[0])
    ref.append('Icddrb')
    ref_code.append(None)
    ## source BSH term
    s1_row = s1[s1['test_key']==test_key]
#     print(s1_row)
    test_keys.append(test_key)
    name.append(s1_row['test_name'].values[0])
    ref.append('Bangladesh Specialized Hospital')
    ref_code.append(None)
    ## source Eye hospital term
    s2_row = s2[s2['test_key']==test_key]
    if(not s2_row.empty):
        test_keys.append(test_key)
        name.append(s2_row['test_name'].values[0])
        ref.append('Bangladesh Eye Hospital')
        ref_code.append(None)

In [62]:
name

[]

In [63]:
test_name_df = pd.DataFrame(
    {'_id': list(range(1, len(test_keys)+1)),
     'test_key': test_keys,
     'name': name,
     'ref': ref,
     'ref_code': ref_code
    })
test_name_df

Empty DataFrame
Columns: [_id, test_key, name, ref, ref_code]
Index: []

In [75]:
test_name_df.to_csv(data_dir + 'std/testname.csv', index=False)